[package]
name = "sin_synth"
version = "0.1.0"
authors = ["airtoxin <airtoxin@icloud.com>"]
edition = "2018"

[dependencies]
vst = "0.0.2"
time = "0.1.42"

[lib]
name = "sin_synth"
crate-type = ["cdylib"]
